# Generated by Django 3.1 on 2022-06-01 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Home.unit'),
            preserve_default=False,
        ),
    ]
