# Generated by Django 3.1 on 2022-06-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_question_result_kanji_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
